processor:
  build: ../data-processor/
  links:
    - rabbitmq
    - db
  env_file: .env

rabbitmq:
  image: rabbitmq:3.5.3-management
  ports:
    - 55672:15672
  hostname: qa-engine-rabbit

db:
  image: postgres:9.4.1
  ports:
    - 55432:5432
  env_file: .env

metis:
  build: ../Metis/
  env_file: .env
  links:
    - db
    - processor
    - rabbitmq
  ports:
    - 54000:4000
