version: "3"
services:
  processor:
    build: ../data-processor/
    links:
      - rabbitmq
      - db
    env_file: .env

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - 55672:15672
    hostname: rabbitmq

  db:
    image: postgres:9.4.7
    ports:
      - 55432:5432
    env_file: .env
    hostname: db

  metis:
    build: ../Metis/
    env_file: .env
    links:
      - db
      - processor
      - rabbitmq
    ports:
      - 54000:4000
